version: "3.9"
services:
  client:
    image: alovegren/shopping-cart-client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    image: alovegren/shopping-cart-server
    container_name: server
    ports:
      - 5001:5001
    environment:
      - DB